### ISSUE TITLE
 Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by alwaysbusy** [yorknouse/account#21]
Line 17 of admin-sessions.jade

    Cannot read property 'user' of undefined
       at eval (eval at <anonymous> (account/node_modules/jade/lib/index.js:218:8), <anonymous>:177:35)
       at eval (eval at <anonymous> (account/node_modules/jade/lib/index.js:218:8), <anonymous>:330:4)
       at eval (eval at <anonymous> (account/node_modules/jade/lib/index.js:218:8), <anonymous>:482:22)
       at res (account/node_modules/jade/lib/index.js:219:38)
       at Object.exports.renderFile (account/node_modules/jade/lib/index.js:380:38)
       at Object.exports.renderFile (account/node_modules/jade/lib/index.js:370:21)
       at View.exports.__express [as engine (account/node_modules/jade/lib/index.js:417:11)
       at View.render (account/node_modules/express/lib/view.js:126:8)
       at tryRender (account/node_modules/express/lib/application.js:639:10)
       at EventEmitter.render (account/node_modules/express/lib/application.js:591:3)

**Comment by alwaysbusy** [comment]
Fixed in fd39772
